### ISSUE TITLE
Broken Pipe?

### ISSUE THREAD

**Issue by dsiah** [Space-Cadets/Oberon#5]
After a bunch of requests the API dies giving this error. The only corrective action currently is restarting the server.

```
127.0.0.1 - - [09/Feb/2016 20:55:27] "GET /instructors/Anany%20Levitin HTTP/1.1" 200 -
Error on request:
Traceback (most recent call last):
  File "/Users/dsiah/Documents/Languages/Python/oberon-venv/lib/python2.7/site-packages/werkzeug/serving.py", line 194, in run_wsgi
    execute(self.server.app)
  File "/Users/dsiah/Documents/Languages/Python/oberon-venv/lib/python2.7/site-packages/werkzeug/serving.py", line 185, in execute
    write(data)
  File "/Users/dsiah/Documents/Languages/Python/oberon-venv/lib/python2.7/site-packages/werkzeug/serving.py", line 160, in write
    self.send_header('Server', self.version_string())
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 401, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
```

Any ideas?

**Comment by kentkwu** [comment]
Broken Pipe occurs when one end of the connection tries sending data while the other end has already closed the connection.
